runtime: python
env: flex

runtime_config:
    operating_system: "ubuntu18"
    runtime_version: "3.9"

entrypoint: streamlit run About.py --server.port $PORT

env_variables:
    SEARCH_ENGINE_ID: your-enterprise-search-engine-id